name: Build and Push

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # allows manual triggering of the workflow

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  REPO_NAME: orbitvis-repo

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Google Cloud
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      # Build and push Docker images
      - name: Build and push catalog image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: cmd/catalog/Dockerfile
          push: true
          tags: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/catalog:latest

      - name: Build and push propagator image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: cmd/propagator/Dockerfile
          push: true
          tags: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/propagator:latest

      - name: Build and push spatial image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: cmd/spatial/Dockerfile
          push: true
          tags: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/spatial:latest
